---
AWSTemplateFormatVersion: 2010-09-09

Description: WordPress on AWS - Creates Pipeline to Deploy VidCruiter WP Theme

Metadata:

  Authors:
    Description: Jessica Lopez (jlopez@vidcruiter.com)

  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Pipeline Parameters
      Parameters:
        - PipelineBucket
        - RepoConnection
    ParameterLabels:
      PipelineBucket:
        default: Pipeline Bucket Name
      RepoConnection:
        default: Codestar Bitbucket Connection ARN
      RepoName:
        default: Name of the repository for the pipeline
      DeployBranch:
        default: Branch for the deployment
      MountPoint:
        default: Location in the container to mount the file system

Parameters:
  EFS:
    AllowedPattern: ^(fs-)([a-z0-9]{8,17})$
    Description: The Amazon EFS file system id.
    Type: String
  MountPoint:
    Description: Location in the container to mount the file system.
    Default: /efs
    Type: String
  PipelineBucket:
    Description: Pipeline Bucket Name.
    Type: String
  RepoConnection:
    Description: Connection ARN for Bitbucket.
    Type: String
  RepoName:
    Description: Name of the repository for the pipeline.
    Type: String
  DeployBranch:
    Description: Branch for the deployment.
    Type: String
  NumberOfSubnets:
    AllowedValues:
    - 2
    - 3
    - 4
    - 5
    - 6
    Default: 3
    Description: Number of subnets. This must match your selections in the list of Subnets below.
    Type: String
  Subnet:
    Description: Subnets of the vpc to have access to EFS
    Type: List<AWS::EC2::Subnet::Id>
  VPCId:
    Description: VPC to deploy Codebuild
    Type: String
  SG:
    Description: Select the efs security group.
    Type: AWS::EC2::SecurityGroup::Id
  WPDirectory:
    AllowedPattern: ^([a-zA-Z0-9])([a-zA-Z0-9_-])*([a-zA-Z0-9])$
    Description: The WordPress site directory.
    Type: String

Conditions:
  NumberOfSubnets1:
    !Equals [ 1, !Ref NumberOfSubnets ]
  NumberOfSubnets2:
    !Equals [ 2, !Ref NumberOfSubnets ]
  NumberOfSubnets3:
    !Equals [ 3, !Ref NumberOfSubnets ]
  NumberOfSubnets4:
    !Equals [ 4, !Ref NumberOfSubnets ]
  NumberOfSubnets5:
    !Equals [ 5, !Ref NumberOfSubnets ]
  NumberOfSubnets6:
    !Equals [ 6, !Ref NumberOfSubnets ]
  Subnet0: !Or
    - !Condition NumberOfSubnets1
    - !Condition NumberOfSubnets2
    - !Condition NumberOfSubnets3
    - !Condition NumberOfSubnets4
    - !Condition NumberOfSubnets5
    - !Condition NumberOfSubnets6
  Subnet1: !Or
    - !Condition NumberOfSubnets2
    - !Condition NumberOfSubnets3
    - !Condition NumberOfSubnets4
    - !Condition NumberOfSubnets5
    - !Condition NumberOfSubnets6
  Subnet2: !Or
    - !Condition NumberOfSubnets3
    - !Condition NumberOfSubnets4
    - !Condition NumberOfSubnets5
    - !Condition NumberOfSubnets6
  Subnet3: !Or
    - !Condition NumberOfSubnets4
    - !Condition NumberOfSubnets5
    - !Condition NumberOfSubnets6
  Subnet4: !Or
    - !Condition NumberOfSubnets5
    - !Condition NumberOfSubnets6
  Subnet5: !Condition NumberOfSubnets6

Resources:
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - codebuild.amazonaws.com

  CodeBuildServicePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CodeBuildServicePolicy
      Roles:
        - !Ref CodeBuildServiceRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "arn:aws:logs:*:*:*"
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucketAcl
              - s3:PutBucketAcl
              - s3:GetBucketLocation
              - s3:GetBucketVersioning
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'PipelineBucket'
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:GetObjectVersion
            Resource:
            - !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref 'PipelineBucket'
                - /*
          - Effect: Allow
            Action:
              - codebuild:CreateReportGroup
              - codebuild:CreateReport
              - codebuild:UpdateReport
              - codebuild:BatchPutTestCases
              - codebuild:BatchPutCodeCoverages
            Resource: "arn:aws:codebuild:*:*:report-group/*"
          - Effect: Allow
            Action:
              - ec2:CreateNetworkInterface
              - ec2:DescribeDhcpOptions
              - ec2:DescribeNetworkInterfaces
              - ec2:DeleteNetworkInterface
              - ec2:DescribeSubnets
              - ec2:DescribeSecurityGroups
              - ec2:DescribeVpcs
            Resource: '*'
          - Effect: Allow
            Action:
              - ec2:CreateNetworkInterfacePermission
            Resource: arn:aws:ec2:*:*:network-interface/*
            Condition:
              StringLike:
                ec2:Subnet:
                  - arn:aws:ec2:*:*:subnet/*
                ec2:AuthorizedService: codebuild.amazonaws.com

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    DependsOn: [ CodeBuildServicePolicy ]
    Properties:
      Name: !Join [ '', [ 'Build-', !Ref 'AWS::StackName' ] ]
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/amazonlinux2-x86_64-standard:3.0'
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: BUILD_ARTIFACT_BUCKET
            Value: !Ref PipelineBucket
          - Name: MOUNT_POINT
            Value: !Ref MountPoint
          - Name: WP_DIRECTORY
            Value: !Ref WPDirectory
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      VpcConfig:
        SecurityGroupIds:
        - Ref: SG
        Subnets:
          !If
            [ NumberOfSubnets1,
            [ !Select [ 0, !Ref Subnet ] ],
            !If
              [ NumberOfSubnets2,
              [ !Select [ 0, !Ref Subnet ], !Select [ 1, !Ref Subnet ] ],
              !If
                [ NumberOfSubnets3,
                [ !Select [ 0, !Ref Subnet ], !Select [ 1, !Ref Subnet ], !Select [ 2, !Ref Subnet ] ],
                !If
                  [ NumberOfSubnets4,
                  [ !Select [ 0, !Ref Subnet ], !Select [ 1, !Ref Subnet ], !Select [ 2, !Ref Subnet ], !Select [ 3, !Ref Subnet ] ],
                  !If
                    [ NumberOfSubnets5,
                    [ !Select [ 0, !Ref Subnet ], !Select [ 1, !Ref Subnet ], !Select [ 2, !Ref Subnet ], !Select [ 3, !Ref Subnet ], !Select [ 4, !Ref Subnet ] ],
                    [ !Select [ 0, !Ref Subnet ], !Select [ 1, !Ref Subnet ], !Select [ 2, !Ref Subnet ], !Select [ 3, !Ref Subnet ], !Select [ 4, !Ref Subnet ], !Select [ 5, !Ref Subnet ] ]
                    ]
                  ]
                ]
              ]
            ]
        VpcId: !Ref VPCId
      FileSystemLocations:
      - Identifier: 'staging_efs'
        Location: !Sub '${EFS}.efs.${AWS::Region}.amazonaws.com:/'
        MountOptions: "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2"
        MountPoint: !Ref MountPoint
        Type: EFS

  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - codepipeline.amazonaws.com

  CodePipelineServicePolicy:
    Type: AWS::IAM::Policy
    DependsOn: [ CodeBuildProject ]
    Properties:
      PolicyName: CodePipelineServicePolicy
      Roles:
        - !Ref 'CodePipelineServiceRole'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'PipelineBucket'
            Action:
              - s3:ListBucket
              - s3:GetBucketAcl
              - s3:PutBucketAcl
              - s3:GetBucketLocation
              - s3:GetBucketVersioning
          - Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'PipelineBucket'
                  - /*
            Action:
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:GetObject
              - s3:GetObjectVersion
          - Effect: Allow
            Action:
              - codestar-connections:UseConnection
            Resource:
              - !Ref 'RepoConnection'
          - Effect: Allow
            Action:
              - appconfig:StartDeployment
              - appconfig:GetDeployment
              - appconfig:StopDeployment
            Resource: '*'
          - Effect: Allow
            Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - codebuild:StopBuild
            Resource: !GetAtt 'CodeBuildProject.Arn'

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn: [ CodePipelineServiceRole, CodeBuildProject ]
    Properties:
      RoleArn: !GetAtt 'CodePipelineServiceRole.Arn'
      ArtifactStore:
        Type: S3
        Location:
          !Ref PipelineBucket
      Stages:
        -
          Name: Bitbucket
          Actions:
          - Name: ApplicationSource
            InputArtifacts: []
            ActionTypeId:
              Version: '1'
              Owner: AWS
              Category: Source
              Provider: CodeStarSourceConnection
            OutputArtifacts:
              - Name: SourceArtifact
            RunOrder: 1
            Configuration:
              ConnectionArn: !Ref 'RepoConnection'
              FullRepositoryId: !Join
                - ''
                - - vidcruiter/
                  - !Ref 'RepoName'
              BranchName: !Ref 'DeployBranch'
              OutputArtifactFormat: CODE_ZIP
        -
          Name: Deployment
          Actions:
            -
              Name: DeploymentAction
              InputArtifacts:
                -
                  Name: SourceArtifact
              ActionTypeId:
                Version: '1'
                Owner: AWS
                Category: Build
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildProject
              RunOrder: 1
